# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-30 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_heading', models.CharField(db_index=True, max_length=200)),
                ('post_body', models.CharField(db_index=True, max_length=200)),
                ('post_picture', models.ImageField(upload_to='carousels/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_image', models.ImageField(upload_to='carousels/%Y/%m/%d')),
                ('carousel_header', models.CharField(db_index=True, max_length=200)),
                ('carousel_body', models.CharField(db_index=True, max_length=200)),
            ],
        ),
    ]
