# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-01 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0004_auto_20171130_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
