# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-01 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0005_auto_20171130_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_body',
            field=models.TextField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_picture',
            field=models.ImageField(upload_to='blog/%Y/%m/%d'),
        ),
    ]
