# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-01 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0006_auto_20171130_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_picture',
            field=models.ImageField(upload_to='media/blog/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='carousel_image',
            field=models.ImageField(upload_to='media/carousels/%Y/%m/%d'),
        ),
    ]
