# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-01 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0009_blogpost_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_picture',
            field=models.ImageField(upload_to='blogpost/%Y'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='carousel_image',
            field=models.ImageField(upload_to='media/carousels/%Y'),
        ),
    ]
