# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-01 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0010_auto_20171201_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_body',
            field=models.TextField(db_index=True),
        ),
    ]
