# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-01 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0011_auto_20171201_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='carousel_image',
        ),
    ]
