# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_bestseller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestseller',
            name='product',
        ),
        migrations.DeleteModel(
            name='Bestseller',
        ),
    ]
