# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20171128_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_tag',
            field=models.TextField(blank=True),
        ),
    ]
