# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-03 05:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20171203_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={},
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
