# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-29 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20171125_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='USA', max_length=100),
            preserve_default=False,
        ),
    ]
